/** How much of a file the content sniff reads. Markers past this are missed; globs remain the escape hatch. */
export const SNIFF_BYTES = 4096;

/** Path shapes that are generated by convention, independent of content. */
const PATH_PATTERNS: RegExp[] = [
  /(^|\/)(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|uv\.lock|Cargo\.lock|poetry\.lock|composer\.lock|Gemfile\.lock|go\.sum|flake\.lock)$/,
  /\.lock$/,
  /\.min\.(js|css|mjs)$/,
  /\.(js|mjs|cjs|css)\.map$/,
  /(^|\/)__snapshots__\//,
  /\.snap$/,
  /_pb2(_grpc)?\.pyi?$/,
  /\.pb\.(go|cc|h|swift|rb|dart)$/,
  /\.(g|freezed|gr)\.dart$/,
  /\.generated\.[^/]+$/,
  /(^|\/)(generated|__generated__|_generated)\//,
  /(^|\/)(dist|build)\/[^/]+\.(js|css)$/,
];

/** Marker phrases the common code generators put in a file header. */
const CONTENT_MARKERS: RegExp[] = [
  /@generated\b/,
  /\bDO NOT EDIT\b/,
  /\bCode generated by\b/,
  /\b[Aa]uto-?generated\b/,
  /\bautomatically generated\b/i,
];

/** Generators write their marker in a comment; prose or code that mentions one does not count. */
const COMMENT_LINE = /^\s*(#|\/\/|\/\*|\*|--|<!--|;|"""|'''|=begin|%|REM\b|@rem\b)/i;

/**
 * True when `path` matches a generated-file convention or the first bytes carry
 * a generator marker. `head` may be null when nothing could be read; binary
 * content never counts as generated here.
 */
export function looksGenerated(path: string, head: Buffer | null): boolean {
  if (PATH_PATTERNS.some((re) => re.test(path))) return true;
  if (head == null || head.length === 0) return false;
  const n = Math.min(head.length, SNIFF_BYTES);
  for (let i = 0; i < n; i++) if (head[i] === 0) return false;
  const text = head.subarray(0, n).toString('utf8');
  return text.split('\n').some((line) => COMMENT_LINE.test(line) && CONTENT_MARKERS.some((re) => re.test(line)));
}
