import { Command, InvalidArgumentError, type Option } from 'commander';

/**
 * `diffle completion <shell>`: the completion script for one shell.
 *
 * The scripts are generated by walking the commander tree, so the commands and
 * flags they offer cannot drift from the CLI. Only what a *value* completes to is
 * hand-written, in FLAG_VALUES and ARG_VALUES below; anything missing there
 * completes to nothing, so a new flag degrades quietly instead of breaking.
 */

/** Shells with a generator. */
export const SHELLS = ['bash', 'zsh', 'fish'] as const;
export type Shell = (typeof SHELLS)[number];

/** Candidates for one value: a fixed word list plus at most one dynamic source. */
interface Source {
  kind: 'none' | 'rev' | 'file' | 'dir';
  words: readonly string[];
}

const NONE: Source = { kind: 'none', words: [] };
const FILE: Source = { kind: 'file', words: [] };
const DIR: Source = { kind: 'dir', words: [] };
const REV: Source = { kind: 'rev', words: [] };
/** A closed set of values, e.g. `--format prompt|json`. */
const oneOf = (...words: string[]): Source => ({ kind: 'none', words });
/** A mode argument: a named mode, or any revspec. */
const MODE: Source = { kind: 'rev', words: ['working', 'branch', 'pr'] };

/**
 * What the value of each flag completes to, keyed by the flag's name (its long
 * spelling without dashes). A flag that takes a value and is not listed here
 * completes to nothing, which is the right answer for a port or an author label.
 */
const FLAG_VALUES: Record<string, Source> = {
  C: DIR,
  comment: FILE,
  path: FILE,
  state: oneOf('open', 'resolved', 'all'),
  format: oneOf('prompt', 'json'),
};

/**
 * What each positional argument completes to, keyed by `<command path> <argument>`.
 * Unlisted arguments complete to nothing: thread ids, globs and free text have no
 * candidates to offer.
 */
const ARG_VALUES: Record<string, Source> = {
  'diffle revs': REV,
  'diffle branch base': REV,
  'diffle export mode': MODE,
  'diffle comment add payload': FILE,
  'diffle completion shell': oneOf(...SHELLS),
};

/** One option, as the shells offer it. */
interface Flag {
  short?: string;
  long?: string;
  description: string;
  /** null for a switch: the next word is not its value. */
  value: Source | null;
}

/** One command in the tree, with everything a shell needs to complete after it. */
interface Node {
  /** The command path, e.g. `diffle comment add`. */
  path: string;
  subcommands: { name: string; description: string }[];
  /** Every flag accepted here, this command's own and its ancestors'. */
  flags: Flag[];
  /** What a bare word completes to. */
  value: Source;
}

const HELP: Flag = { short: '-h', long: '--help', description: 'display help for command', value: null };

const spellings = (f: Flag): string[] => [f.short, f.long].filter((s): s is string => s != null);

/** The first clause of a description: a completion menu has no room for the rest. */
function brief(text: string): string {
  const clause = text.split(/ \(|: |; /)[0]!.trim().replace(/[,:;]$/, '');
  // Too short to be a clause: the parenthesis belongs to a value, as in "open (default), resolved, or all".
  const kept = clause.length >= 12 ? clause : text.trim();
  return kept.length <= 72 ? kept : kept.slice(0, 69).replace(/\s+\S*$/, '') + '...';
}

function flagOf(o: Option): Flag {
  return {
    short: o.short,
    long: o.long,
    description: brief(o.description),
    // Commander consumes the next word for an optional value too, so both take one.
    value: o.required || o.optional ? (FLAG_VALUES[o.name()] ?? NONE) : null,
  };
}

/** Ancestor flags stay available after a subcommand name, minus the ones it redefines. */
function inherit(own: Flag[], inherited: Flag[]): Flag[] {
  const taken = new Set(own.flatMap(spellings));
  return [...own, ...inherited.filter((f) => !spellings(f).some((s) => taken.has(s)))];
}

/** Flattens the command tree; every command's arguments complete alike, so the first speaks for all. */
function nodes(root: Command): Node[] {
  const out: Node[] = [];
  const visit = (cmd: Command, path: string, ancestors: Flag[]) => {
    const flags = inherit([...cmd.options.filter((o) => !o.hidden).map(flagOf), HELP], ancestors);
    const subcommands = cmd.commands.map((c) => ({ name: c.name(), description: brief(c.description()) }));
    if (subcommands.length && !subcommands.some((s) => s.name === 'help')) {
      subcommands.push({ name: 'help', description: 'display help for a command' });
    }
    const arg = cmd.registeredArguments[0];
    const value = (arg && ARG_VALUES[`${path} ${arg.name()}`]) ?? NONE;
    out.push({ path, subcommands, flags, value });
    // The implicit `help` command takes a sibling's name.
    if (subcommands.length) out.push({ path: `${path} help`, subcommands: [], flags, value: oneOf(...subcommands.filter((s) => s.name !== 'help').map((s) => s.name)) });
    for (const c of cmd.commands) visit(c, `${path} ${c.name()}`, flags);
  };
  visit(root, root.name(), []);
  return out;
}

/** Flag spellings whose next word is a value, not a command. */
function valuedSpellings(ns: Node[]): string[] {
  const out = new Set<string>();
  for (const n of ns) for (const f of n.flags) if (f.value) for (const s of spellings(f)) out.add(s);
  return [...out].sort();
}

/** Groups flags by the value they take, so each set of candidates is emitted once. */
function byValue(ns: Node[]): { flags: string[]; value: Source }[] {
  const groups = new Map<string, { flags: Set<string>; value: Source }>();
  for (const n of ns) {
    for (const f of n.flags) {
      if (!f.value || (f.value.kind === 'none' && f.value.words.length === 0)) continue;
      const key = `${f.value.kind} ${f.value.words.join(' ')}`;
      const group = groups.get(key) ?? { flags: new Set<string>(), value: f.value };
      for (const s of spellings(f)) group.flags.add(s);
      groups.set(key, group);
    }
  }
  return [...groups.values()].map((g) => ({ flags: [...g.flags].sort(), value: g.value }));
}

const REV_COMMAND = "git for-each-ref --format='%(refname:short)' refs/heads refs/tags refs/remotes 2>/dev/null";
/** Quotes text for bash and zsh, where a single quote can only be spliced in from outside. */
const sq = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;
/** Quotes text for fish, which escapes a backslash and a single quote inside single quotes. */
const fq = (s: string) => `'${s.replace(/[\\']/g, (m) => `\\${m}`)}'`;

function bashScript(ns: Node[]): string {
  const files = `COMPREPLY+=($(compgen -f -- "$cur")); compopt -o filenames 2>/dev/null`;
  const dirs = `COMPREPLY+=($(compgen -d -- "$cur")); compopt -o filenames 2>/dev/null`;
  const value = (v: Source) => {
    const lines = v.words.length ? [`COMPREPLY+=($(compgen -W "${v.words.join(' ')}" -- "$cur"))`] : [];
    if (v.kind === 'rev') lines.push(`COMPREPLY+=($(compgen -W "$(_diffle_revs)" -- "$cur"))`);
    if (v.kind === 'file') lines.push(files);
    if (v.kind === 'dir') lines.push(dirs);
    return lines.join('; ');
  };
  return [
    '# diffle completion for bash. Generated by `diffle completion bash`.',
    '# Load it with: eval "$(diffle completion bash)"; regenerate it after upgrading diffle.',
    '',
    '_diffle_revs() {',
    "  printf 'HEAD\\n'",
    `  ${REV_COMMAND}`,
    '}',
    '',
    '_diffle() {',
    '  local cur prev cmd w i subs flags kind vals',
    '  cur="${COMP_WORDS[COMP_CWORD]}"',
    '  prev="${COMP_WORDS[COMP_CWORD-1]}"',
    '  # Flags that take a value: the word after one of them is that value, never a command.',
    `  local valued=" ${valuedSpellings(ns).join(' ')} "`,
    '',
    '  # Where the cursor is in the command tree: the words that name a subcommand.',
    '  cmd="diffle"',
    '  for ((i = 1; i < COMP_CWORD; i++)); do',
    '    w="${COMP_WORDS[i]}"',
    '    [[ $w == -* ]] && continue',
    '    [[ $valued == *" ${COMP_WORDS[i-1]} "* ]] && continue',
    '    case "$cmd $w" in',
    `      ${ns.filter((n) => n.path !== 'diffle').map((n) => `"${n.path}"`).join('|')}) cmd="$cmd $w" ;;`,
    '    esac',
    '  done',
    '',
    '  # Right after such a flag, only its value is a candidate.',
    '  if [[ $valued == *" $prev "* ]]; then',
    '    COMPREPLY=()',
    '    case "$prev" in',
    ...byValue(ns).map((g) => `      ${g.flags.join('|')}) ${value(g.value)} ;;`),
    '    esac',
    '    return',
    '  fi',
    '',
    '  kind=none',
    '  vals=""',
    '  case "$cmd" in',
    ...ns.flatMap((n) => [
      `    "${n.path}")`,
      `      subs="${n.subcommands.map((s) => s.name).join(' ')}"`,
      `      flags="${n.flags.flatMap(spellings).join(' ')}"`,
      `      kind=${n.value.kind} vals="${n.value.words.join(' ')}" ;;`,
    ]),
    '  esac',
    '',
    '  if [[ $cur == -* ]]; then',
    '    COMPREPLY=($(compgen -W "$flags" -- "$cur"))',
    '    return',
    '  fi',
    '  COMPREPLY=($(compgen -W "$subs $vals" -- "$cur"))',
    '  case "$kind" in',
    `    rev) COMPREPLY+=($(compgen -W "$(_diffle_revs)" -- "$cur")) ;;`,
    `    file) ${files} ;;`,
    `    dir) ${dirs} ;;`,
    '  esac',
    '}',
    'complete -F _diffle diffle',
    '',
  ].join('\n');
}

function zshScript(ns: Node[]): string {
  const entry = (name: string, description: string) => sq(description ? `${name}:${description}` : name);
  const described = (items: { name: string; description: string }[]) => items.map((i) => entry(i.name, i.description)).join(' ');
  const flagEntries = (flags: Flag[]) => flags.flatMap((f) => spellings(f).map((s) => entry(s, f.description))).join(' ');
  const value = (v: Source) => {
    const lines = v.words.length ? [`vals=(${v.words.join(' ')}); _describe -t values value vals`] : [];
    if (v.kind === 'rev') lines.push('_diffle_revs');
    if (v.kind === 'file') lines.push('_files');
    if (v.kind === 'dir') lines.push('_directories');
    return lines.join('; ');
  };
  return [
    '#compdef diffle',
    '# diffle completion for zsh. Generated by `diffle completion zsh`.',
    '# Load it with: eval "$(diffle completion zsh)"; or save it as _diffle in your fpath.',
    '',
    '_diffle_revs() {',
    '  local -a revs',
    `  revs=(HEAD \${(f)"$(${REV_COMMAND})"})`,
    '  _describe -t revs rev revs',
    '}',
    '',
    '_diffle() {',
    '  local cur prev cmd w kind i',
    '  local -a subs flags vals',
    '  cur=${words[CURRENT]}',
    '  prev=${words[CURRENT-1]}',
    '  # Flags that take a value: the word after one of them is that value, never a command.',
    `  local valued=" ${valuedSpellings(ns).join(' ')} "`,
    '',
    '  # Where the cursor is in the command tree: the words that name a subcommand.',
    '  cmd=diffle',
    '  for (( i = 2; i < CURRENT; i++ )); do',
    '    w=${words[i]}',
    '    [[ $w == -* ]] && continue',
    '    [[ $valued == *" ${words[i-1]} "* ]] && continue',
    '    case "$cmd $w" in',
    `      (${ns.filter((n) => n.path !== 'diffle').map((n) => `"${n.path}"`).join('|')}) cmd="$cmd $w" ;;`,
    '    esac',
    '  done',
    '',
    '  # Right after such a flag, only its value is a candidate.',
    '  if [[ $valued == *" $prev "* ]]; then',
    '    case $prev in',
    ...byValue(ns).map((g) => `      (${g.flags.join('|')}) ${value(g.value)} ;;`),
    '    esac',
    '    return',
    '  fi',
    '',
    '  kind=none',
    '  vals=()',
    '  case "$cmd" in',
    ...ns.flatMap((n) => [
      `    ("${n.path}")`,
      `      subs=(${described(n.subcommands)})`,
      `      flags=(${flagEntries(n.flags)})`,
      `      kind=${n.value.kind} vals=(${n.value.words.join(' ')}) ;;`,
    ]),
    '  esac',
    '',
    '  if [[ $cur == -* ]]; then',
    '    _describe -t options option flags',
    '    return',
    '  fi',
    '  (( $#subs )) && _describe -t commands command subs',
    '  (( $#vals )) && _describe -t values value vals',
    '  case $kind in',
    '    (rev) _diffle_revs ;;',
    '    (file) _files ;;',
    '    (dir) _directories ;;',
    '  esac',
    '  return 0',
    '}',
    '',
    '# Autoloaded from the fpath, or sourced: either way one line registers it.',
    'if [ "$funcstack[1]" = "_diffle" ]; then',
    '  _diffle "$@"',
    'else',
    '  compdef _diffle diffle',
    'fi',
    '',
  ].join('\n');
}

function fishScript(ns: Node[]): string {
  /** The `complete` arguments for a value: what follows the flag, or a bare word. */
  const value = (v: Source, positional: boolean): string[] => {
    const args = [...v.words];
    if (v.kind === 'rev') args.push('(__diffle_revs)');
    if (v.kind === 'dir') args.push('(__fish_complete_directories)');
    const out = positional ? [] : [v.kind === 'file' ? '-r -F' : '-x'];
    if (args.length) out.push(`-a ${fq(args.join(' '))}`);
    if (positional && v.kind === 'file') out.push('-F');
    return out;
  };
  const at = (path: string) => `-n ${fq(`__diffle_at ${JSON.stringify(path)}`)}`;
  const describe = (description: string) => (description ? ` -d ${fq(description)}` : '');
  const lines = [
    '# diffle completion for fish. Generated by `diffle completion fish`.',
    '# Save it as ~/.config/fish/completions/diffle.fish; regenerate it after upgrading diffle.',
    '',
    'function __diffle_revs',
    '  echo HEAD',
    `  ${REV_COMMAND}`,
    'end',
    '',
    'function __diffle_path --description "the diffle command the cursor is in"',
    `  set -l valued ${valuedSpellings(ns).join(' ')}`,
    '  set -l tokens (commandline -pco)',
    '  if set -q tokens[1]',
    '    set -e tokens[1]',
    '  end',
    '  set -l cmd diffle',
    '  set -l skip 0',
    '  for t in $tokens',
    '    if test $skip -eq 1',
    '      set skip 0',
    '    else if string match -q -- "-*" $t',
    '      # Its value follows, and is never a command name.',
    '      if contains -- $t $valued',
    '        set skip 1',
    '      end',
    '    else',
    '      switch "$cmd $t"',
    `        case ${ns.filter((n) => n.path !== 'diffle').map((n) => fq(n.path)).join(' ')}`,
    '          set cmd "$cmd $t"',
    '      end',
    '    end',
    '  end',
    '  echo $cmd',
    'end',
    '',
    'function __diffle_at --description "true when the cursor is in the given diffle command"',
    '  test (__diffle_path) = "$argv[1]"',
    'end',
    '',
    '# Nothing completes to a file unless a rule below says so.',
    'complete -c diffle -f',
  ];
  for (const n of ns) {
    lines.push('', `# ${n.path}`);
    for (const s of n.subcommands) lines.push(`complete -c diffle ${at(n.path)} -a ${fq(s.name)}${describe(s.description)}`);
    const positional = value(n.value, true);
    if (positional.length) lines.push(`complete -c diffle ${at(n.path)} ${positional.join(' ')}`);
    for (const f of n.flags) {
      const spelling = [f.short && `-s ${f.short.slice(1)}`, f.long && `-l ${f.long.slice(2)}`].filter(Boolean).join(' ');
      const val = f.value ? value(f.value, false).join(' ') : '';
      lines.push(`complete -c diffle ${at(n.path)} ${spelling}${val ? ` ${val}` : ''}${describe(f.description)}`);
    }
  }
  return lines.join('\n') + '\n';
}

/** The completion script for one shell, generated from the CLI's own command tree. */
export function completionScript(root: Command, shell: Shell): string {
  const ns = nodes(root);
  if (shell === 'bash') return bashScript(ns);
  if (shell === 'zsh') return zshScript(ns);
  return fishScript(ns);
}

const parseShell = (raw: string): Shell => {
  if (!(SHELLS as readonly string[]).includes(raw)) throw new InvalidArgumentError(`expected ${SHELLS.join(', ')}`);
  return raw as Shell;
};

/** `diffle completion <shell>`. */
export function completionCommand(): Command {
  return new Command('completion')
    .description('print a shell completion script for bash, zsh or fish')
    .argument('<shell>', `the shell to generate for: ${SHELLS.join(', ')}`, parseShell)
    .addHelpText(
      'after',
      `
Load it from your shell's startup file:
  bash   eval "$(diffle completion bash)"        in ~/.bashrc
  zsh    eval "$(diffle completion zsh)"         in ~/.zshrc, after compinit
  fish   diffle completion fish > ~/.config/fish/completions/diffle.fish

The script lists the commands and flags of the diffle that printed it; print it
again after upgrading.`,
    )
    .action((shell: Shell, _o, cmd: Command) => {
      process.stdout.write(completionScript(cmd.parent ?? cmd, shell));
    });
}
