/**
 * The fixture repository: a small, realistic project with a scripted history that
 * exercises every diff shape diffle renders. The e2e tests review it, and
 * `npm run fixture` builds it for hands-on testing.
 *
 * Every commit has a fixed author, committer and date, and every file is written
 * byte for byte, so the history hashes the same on every machine and platform.
 * `test/fixture/repo.test.ts` pins those hashes: a change to this file that alters
 * the history is meant to fail there, and its screenshots must be re-accepted.
 *
 *     A - B - C(v0.1.0) - D --------- H   main
 *                          \
 *                           E - F - G - I  feature/refunds   (checked out)
 *
 * `feature/refunds` against `main` shows: multi-hunk edits, an added and a deleted
 * file, a rename with edits and a pure rename, a mode change, a binary change, files
 * flagged generated by path, by content and by gitattribute, a lockfile, a path with
 * a space and non-ASCII letters, an empty file, a file without a trailing newline,
 * CRLF line endings and a minified line. The working tree has a staged edit, an
 * unstaged edit and an untracked file for `working` mode.
 */
import { execFileSync } from 'node:child_process';
import { chmod, mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

/** The branch checked out when the build finishes. */
export const FEATURE_BRANCH = 'feature/refunds';
export const MAIN_BRANCH = 'main';
export const TAG = 'v0.1.0';

/** Comparisons worth opening, with what each one shows. */
export const REVIEWS: { revs: string; shows: string }[] = [
  { revs: `${MAIN_BRANCH}...${FEATURE_BRANCH}`, shows: 'everything the feature branch added (merge base)' },
  { revs: `${MAIN_BRANCH}..${FEATURE_BRANCH}`, shows: 'the two branches side by side, main’s own fix included' },
  { revs: 'working', shows: 'the staged, unstaged and untracked changes' },
  { revs: `${TAG}..${MAIN_BRANCH}`, shows: 'what main released since the tag' },
  { revs: 'HEAD~1', shows: 'the last commit alone' },
];

const AUTHORS = {
  ada: { name: 'Ada Lovelace', email: 'ada@example.com' },
  grace: { name: 'Grace Hopper', email: 'grace@example.com' },
} as const;

/** The first commit; every later one is an hour after the one before it. */
const EPOCH = Date.UTC(2024, 4, 6, 9, 0, 0);

type Author = keyof typeof AUTHORS;

/** Paths mapped to their new bytes, or to `null` to delete them. */
type Files = Record<string, string | Buffer | null>;

interface Commit {
  message: string;
  author: Author;
  /** Start this commit on a new branch from the current HEAD. */
  branch?: string;
  /** Check this branch out before applying the commit. */
  checkout?: string;
  /** `git mv` pairs, applied before `files`, so a rename with edits lists the edit under the new path. */
  moves?: [from: string, to: string][];
  files?: Files;
  /** Paths to mark executable in the index; the mode bit is set in the index so Windows records it too. */
  exec?: string[];
  /** Annotated tag to create on this commit. */
  tag?: string;
}

/**
 * `source` with each `from` replaced once, in order. A `from` that no longer occurs is a
 * mistake in this file, so it throws instead of leaving the version silently unchanged.
 */
function edit(source: string, ...changes: [from: string, to: string][]): string {
  for (const [from, to] of changes) {
    if (!source.includes(from)) throw new Error(`fixture edit: text not found:\n${from}`);
    source = source.replace(from, to);
  }
  return source;
}

// ---------------------------------------------------------------------------------------------
// File contents. Each constant is one version of one file; the commits below pick them.

const GITATTRIBUTES = `# Batch files keep their CRLF endings on every platform.
*.bat -text
*.png binary
# GitHub collapses this in a review; diffle reads the same attribute.
tally/schema.json linguist-generated=true
`;

const GITIGNORE = `__pycache__/
.venv/
*.egg-info/
dist/
`;

const README_V1 = `# tally

Sums up invoices and expenses from CSV ledgers, one account at a time.

## Usage

\`\`\`sh
tally total ledgers/*.csv
tally total --account travel ledgers/2024-*.csv
\`\`\`

A ledger is a CSV file with the columns \`account\`, \`description\`, \`quantity\`,
\`unit_price\` and an optional \`currency\` (default: EUR).
`;

const README_V2 = `# tally

Sums up invoices and expenses from CSV ledgers, one account at a time.

## Usage

\`\`\`sh
tally total ledgers/*.csv
tally total --account travel ledgers/2024-*.csv
tally total --json ledgers/*.csv | jq .
\`\`\`

A ledger is a CSV file with the columns \`account\`, \`description\`, \`quantity\`,
\`unit_price\` and an optional \`currency\` (default: EUR). Quantities must be
positive; a negative quantity is rejected with the line it appeared on.
`;

/** The unstaged edit in the working tree. */
const README_WORKTREE = `# tally

Sums up invoices, expenses and refunds from CSV ledgers, one account at a time.

## Usage

\`\`\`sh
tally total ledgers/*.csv
tally total --account travel ledgers/2024-*.csv
tally total --json ledgers/*.csv | jq .
\`\`\`

A ledger is a CSV file with the columns \`account\`, \`description\`, \`quantity\`,
\`unit_price\` and an optional \`currency\` (default: EUR).
`;

const PYPROJECT = `[project]
name = "tally"
version = "0.1.0"
description = "Sum up invoices and expenses from CSV ledgers"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
tally = "tally.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 100
`;

const INIT_PY = `"""tally: sum up CSV ledgers."""

__version__ = "0.1.0"
`;

const LEDGER_V1 = `"""Parse ledger CSV files and total them per account."""

from __future__ import annotations

import csv
from dataclasses import dataclass, field
from decimal import Decimal
from pathlib import Path
from typing import Iterable, Iterator


@dataclass(frozen=True)
class Entry:
    """One ledger line: what was bought, for which account, at what price."""

    account: str
    description: str
    quantity: int
    unit_price: Decimal
    currency: str = "EUR"

    @property
    def total(self) -> Decimal:
        return self.unit_price * self.quantity


@dataclass
class Ledger:
    """Entries in file order, queried per account."""

    entries: list[Entry] = field(default_factory=list)

    def add(self, entry: Entry) -> None:
        self.entries.append(entry)

    def accounts(self) -> list[str]:
        seen: dict[str, None] = {}
        for entry in self.entries:
            seen.setdefault(entry.account, None)
        return list(seen)

    def by_account(self, account: str) -> Iterator[Entry]:
        return (entry for entry in self.entries if entry.account == account)

    def total(self, account: str | None = None) -> Decimal:
        entries = self.entries if account is None else self.by_account(account)
        return sum((entry.total for entry in entries), Decimal(0))


COLUMNS = ("account", "description", "quantity", "unit_price", "currency")


def parse_row(row: dict[str, str]) -> Entry:
    """Turn one CSV row into an Entry, defaulting the currency."""
    return Entry(
        account=row["account"].strip(),
        description=row["description"].strip(),
        quantity=int(row["quantity"]),
        unit_price=Decimal(row["unit_price"]),
        currency=(row.get("currency") or "EUR").strip().upper(),
    )


def read_ledger(path: Path) -> Ledger:
    """Read a CSV ledger. A missing column raises KeyError with the column name."""
    ledger = Ledger()
    with path.open(newline="") as handle:
        for row in csv.DictReader(handle):
            ledger.add(parse_row(row))
    return ledger


def merge(ledgers: Iterable[Ledger]) -> Ledger:
    """Concatenate ledgers; later files come after earlier ones."""
    merged = Ledger()
    for ledger in ledgers:
        for entry in ledger.entries:
            merged.add(entry)
    return merged
`;

/** B: totals are rounded per currency. */
const LEDGER_V2 = edit(
  LEDGER_V1,
  [
    'from typing import Iterable, Iterator\n',
    'from typing import Iterable, Iterator\n\nfrom .money import round_amount\n',
  ],
  [
    `    def total(self, account: str | None = None) -> Decimal:
        entries = self.entries if account is None else self.by_account(account)
        return sum((entry.total for entry in entries), Decimal(0))
`,
    `    def total(self, account: str | None = None) -> Decimal:
        """The sum over one account, or over everything; rounded per currency."""
        entries = list(self.entries if account is None else self.by_account(account))
        currencies = {entry.currency for entry in entries}
        if len(currencies) > 1:
            raise ValueError(f"mixed currencies: {', '.join(sorted(currencies))}")
        currency = next(iter(currencies), "EUR")
        return round_amount(sum((entry.total for entry in entries), Decimal(0)), currency)

    def totals_by_currency(self) -> dict[str, Decimal]:
        """One rounded total per currency, in first-seen order."""
        totals: dict[str, Decimal] = {}
        for entry in self.entries:
            totals[entry.currency] = totals.get(entry.currency, Decimal(0)) + entry.total
        return {currency: round_amount(total, currency) for currency, total in totals.items()}
`,
  ],
);

/** E: refund lines. Touches the module docstring, the dataclass, the columns and the parser. */
const LEDGER_V3 = edit(
  LEDGER_V2,
  [
    '"""Parse ledger CSV files and total them per account."""\n',
    '"""Parse ledger CSV files and total them per account.\n\nA line is a sale unless its ``kind`` column says ``refund``; refunds count negative.\n"""\n',
  ],
  ['from typing import Iterable, Iterator\n', 'from typing import Iterable, Iterator, Literal\n'],
  [
    `    unit_price: Decimal
    currency: str = "EUR"

    @property
    def total(self) -> Decimal:
        return self.unit_price * self.quantity
`,
    `    unit_price: Decimal
    currency: str = "EUR"
    kind: Kind = "sale"

    @property
    def total(self) -> Decimal:
        amount = self.unit_price * self.quantity
        return -amount if self.kind == "refund" else amount
`,
  ],
  [
    '@dataclass(frozen=True)\nclass Entry:',
    'Kind = Literal["sale", "refund"]\n\n\n@dataclass(frozen=True)\nclass Entry:',
  ],
  [
    'COLUMNS = ("account", "description", "quantity", "unit_price", "currency")\n',
    'COLUMNS = ("account", "description", "quantity", "unit_price", "currency", "kind")\n',
  ],
  [
    `    """Turn one CSV row into an Entry, defaulting the currency."""
    return Entry(
        account=row["account"].strip(),
        description=row["description"].strip(),
        quantity=int(row["quantity"]),
        unit_price=Decimal(row["unit_price"]),
        currency=(row.get("currency") or "EUR").strip().upper(),
    )
`,
    `    """Turn one CSV row into an Entry, defaulting the currency and the kind."""
    kind = (row.get("kind") or "sale").strip().lower()
    if kind not in ("sale", "refund"):
        raise ValueError(f"unknown kind: {kind!r}")
    return Entry(
        account=row["account"].strip(),
        description=row["description"].strip(),
        quantity=int(row["quantity"]),
        unit_price=Decimal(row["unit_price"]),
        currency=(row.get("currency") or "EUR").strip().upper(),
        kind=kind,
    )
`,
  ],
);

/** F: the money module moved. */
const LEDGER_V4 = edit(LEDGER_V3, ['from .money import round_amount\n', 'from .currency import round_amount\n']);

/** H, on main: negative quantities are rejected. Overlaps E's parser hunk on purpose. */
const LEDGER_MAIN_FIX = edit(LEDGER_V2, [
  `    """Turn one CSV row into an Entry, defaulting the currency."""
    return Entry(
        account=row["account"].strip(),
        description=row["description"].strip(),
        quantity=int(row["quantity"]),
`,
  `    """Turn one CSV row into an Entry, defaulting the currency.

    A negative quantity is a data-entry mistake, never a refund; reject it.
    """
    quantity = int(row["quantity"])
    if quantity < 0:
        raise ValueError(f"negative quantity for {row['description']!r}: {quantity}")
    return Entry(
        account=row["account"].strip(),
        description=row["description"].strip(),
        quantity=quantity,
`,
]);

const MONEY = `"""Currency-aware rounding."""

from decimal import ROUND_HALF_EVEN, Decimal

# Minor units per currency; everything else has two.
_DIGITS = {"JPY": 0, "KWD": 3}


def minor_units(currency: str) -> int:
    """How many decimal places the currency is quoted in."""
    return _DIGITS.get(currency.upper(), 2)


def round_amount(amount: Decimal, currency: str) -> Decimal:
    """Round to the currency's minor unit, bankers' style."""
    return amount.quantize(Decimal(1).scaleb(-minor_units(currency)), rounding=ROUND_HALF_EVEN)
`;

/** F: money.py becomes currency.py and grows formatting. Similar enough for rename detection. */
const CURRENCY = `"""Currency-aware rounding and formatting."""

from decimal import ROUND_HALF_EVEN, Decimal

# Minor units per currency; everything else has two.
_DIGITS = {"JPY": 0, "KWD": 3}
_SYMBOLS = {"EUR": "€", "USD": "$", "GBP": "£", "JPY": "¥"}


def minor_units(currency: str) -> int:
    """How many decimal places the currency is quoted in."""
    return _DIGITS.get(currency.upper(), 2)


def round_amount(amount: Decimal, currency: str) -> Decimal:
    """Round to the currency's minor unit, bankers' style."""
    return amount.quantize(Decimal(1).scaleb(-minor_units(currency)), rounding=ROUND_HALF_EVEN)


def format_amount(amount: Decimal, currency: str) -> str:
    """Render a rounded amount with its symbol, or its code when there is none."""
    rounded = round_amount(amount, currency)
    symbol = _SYMBOLS.get(currency.upper())
    return f"{symbol}{rounded}" if symbol else f"{rounded} {currency.upper()}"
`;

const REFUNDS = `"""Match refund lines against the sales they undo."""

from __future__ import annotations

from collections import defaultdict
from decimal import Decimal

from .currency import round_amount
from .ledger import Entry, Ledger


def unmatched_refunds(ledger: Ledger) -> list[Entry]:
    """Refunds whose account never sold the refunded description."""
    sold: dict[str, set[str]] = defaultdict(set)
    for entry in ledger.entries:
        if entry.kind == "sale":
            sold[entry.account].add(entry.description)
    return [
        entry
        for entry in ledger.entries
        if entry.kind == "refund" and entry.description not in sold[entry.account]
    ]


def net_by_account(ledger: Ledger) -> dict[str, Decimal]:
    """Sales minus refunds per account, rounded in each account's currency."""
    net: dict[str, Decimal] = {}
    currency: dict[str, str] = {}
    for entry in ledger.entries:
        net[entry.account] = net.get(entry.account, Decimal(0)) + entry.total
        currency.setdefault(entry.account, entry.currency)
    return {account: round_amount(total, currency[account]) for account, total in net.items()}
`;

/** E: imports from `.money`; F renames the module. */
const REFUNDS_V1 = edit(REFUNDS, ['from .currency import round_amount\n', 'from .money import round_amount\n']);

/** The staged edit in the working tree. */
const REFUNDS_STAGED = edit(REFUNDS, [
  `    return [
        entry
        for entry in ledger.entries
        if entry.kind == "refund" and entry.description not in sold[entry.account]
    ]
`,
  `    return sorted(
        (
            entry
            for entry in ledger.entries
            if entry.kind == "refund" and entry.description not in sold[entry.account]
        ),
        key=lambda entry: (entry.account, entry.description),
    )
`,
]);

const LEGACY = `"""Reader for the pre-2023 tab-separated ledgers. Kept until the archive is converted."""

from decimal import Decimal
from pathlib import Path

from .ledger import Entry, Ledger


def read_tsv(path: Path) -> Ledger:
    ledger = Ledger()
    for line in path.read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        account, description, quantity, unit_price = line.split("\\t")
        ledger.add(Entry(account, description, int(quantity), Decimal(unit_price)))
    return ledger
`;

const CLI_V1 = `"""Command line entry point."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .ledger import merge, read_ledger


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="tally", description="Sum up CSV ledgers.")
    commands = parser.add_subparsers(dest="command", required=True)
    total = commands.add_parser("total", help="total the given ledgers")
    total.add_argument("files", nargs="+", type=Path)
    total.add_argument("--account", help="only this account")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    ledger = merge(read_ledger(path) for path in args.files)
    if args.account:
        print(f"{args.account}: {ledger.total(args.account)}")
        return 0
    for account in ledger.accounts():
        print(f"{account}: {ledger.total(account)}")
    print(f"total: {ledger.total()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
`;

/** D: `--json`. */
const CLI_V2 = edit(
  CLI_V1,
  ['import argparse\nimport sys\n', 'import argparse\nimport json\nimport sys\n'],
  [
    '    total.add_argument("--account", help="only this account")\n',
    '    total.add_argument("--account", help="only this account")\n    total.add_argument("--json", action="store_true", help="print one JSON object")\n',
  ],
  [
    `    ledger = merge(read_ledger(path) for path in args.files)
    if args.account:
`,
    `    ledger = merge(read_ledger(path) for path in args.files)
    if args.json:
        accounts = [args.account] if args.account else ledger.accounts()
        print(json.dumps({account: str(ledger.total(account)) for account in accounts}, indent=2))
        return 0
    if args.account:
`,
  ],
);

/** I: an empty ledger no longer crashes. */
const CLI_V3 = edit(CLI_V2, [
  `    ledger = merge(read_ledger(path) for path in args.files)
    if args.json:
`,
  `    ledger = merge(read_ledger(path) for path in args.files)
    if not ledger.entries:
        print("no entries", file=sys.stderr)
        return 1
    if args.json:
`,
]);

const TEST_LEDGER_V1 = `from decimal import Decimal
from pathlib import Path

from tally.ledger import Entry, Ledger, parse_row, read_ledger


def test_parse_row_defaults_currency() -> None:
    entry = parse_row({"account": "travel", "description": "train", "quantity": "2", "unit_price": "19.90"})
    assert entry.currency == "EUR"
    assert entry.total == Decimal("39.80")


def test_total_per_account() -> None:
    ledger = Ledger()
    ledger.add(Entry("travel", "train", 2, Decimal("19.90")))
    ledger.add(Entry("office", "paper", 10, Decimal("3.50")))
    assert ledger.total("travel") == Decimal("39.80")
    assert ledger.total() == Decimal("74.80")


def test_read_ledger(tmp_path: Path) -> None:
    csv = tmp_path / "ledger.csv"
    csv.write_text("account,description,quantity,unit_price\\ntravel,train,2,19.90\\n")
    assert read_ledger(csv).accounts() == ["travel"]
`;

/** B: rounding and mixed currencies. */
const TEST_LEDGER_V2 =
  edit(TEST_LEDGER_V1, [
    'from tally.ledger import Entry, Ledger, parse_row, read_ledger\n',
    'import pytest\n\nfrom tally.ledger import Entry, Ledger, parse_row, read_ledger\n',
  ]) +
  `

def test_total_rounds_to_minor_unit() -> None:
    ledger = Ledger()
    ledger.add(Entry("travel", "taxi", 3, Decimal("3.333")))
    assert ledger.total() == Decimal("10.00")


def test_total_refuses_mixed_currencies() -> None:
    ledger = Ledger()
    ledger.add(Entry("travel", "train", 1, Decimal("10"), "EUR"))
    ledger.add(Entry("travel", "tube", 1, Decimal("10"), "GBP"))
    with pytest.raises(ValueError, match="mixed currencies"):
        ledger.total()
    assert ledger.totals_by_currency() == {"EUR": Decimal("10.00"), "GBP": Decimal("10.00")}
`;

/** E: refunds count negative. */
const TEST_LEDGER_V3 =
  TEST_LEDGER_V2 +
  `

def test_refund_counts_negative() -> None:
    ledger = Ledger()
    ledger.add(Entry("travel", "train", 2, Decimal("19.90")))
    ledger.add(Entry("travel", "train", 1, Decimal("19.90"), kind="refund"))
    assert ledger.total("travel") == Decimal("19.90")


def test_parse_row_rejects_unknown_kind() -> None:
    row = {"account": "a", "description": "b", "quantity": "1", "unit_price": "1", "kind": "gift"}
    with pytest.raises(ValueError, match="unknown kind"):
        parse_row(row)
`;

const TEST_REFUNDS = `from decimal import Decimal

from tally.ledger import Entry, Ledger
from tally.refunds import net_by_account, unmatched_refunds


def ledger() -> Ledger:
    result = Ledger()
    result.add(Entry("travel", "train", 2, Decimal("19.90")))
    result.add(Entry("travel", "train", 1, Decimal("19.90"), kind="refund"))
    result.add(Entry("office", "chair", 1, Decimal("120"), kind="refund"))
    return result


def test_unmatched_refunds() -> None:
    assert [entry.description for entry in unmatched_refunds(ledger())] == ["chair"]


def test_net_by_account() -> None:
    assert net_by_account(ledger()) == {"travel": Decimal("19.90"), "office": Decimal("-120.00")}
`;

const SCHEMA_V1 = `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Ledger row",
  "type": "object",
  "required": ["account", "description", "quantity", "unit_price"],
  "properties": {
    "account": { "type": "string" },
    "description": { "type": "string" },
    "quantity": { "type": "integer", "minimum": 0 },
    "unit_price": { "type": "string", "pattern": "^-?[0-9]+(\\\\.[0-9]+)?$" },
    "currency": { "type": "string", "pattern": "^[A-Z]{3}$", "default": "EUR" }
  }
}
`;

const SCHEMA_V2 = edit(SCHEMA_V1, [
  '    "currency": { "type": "string", "pattern": "^[A-Z]{3}$", "default": "EUR" }\n',
  '    "currency": { "type": "string", "pattern": "^[A-Z]{3}$", "default": "EUR" },\n    "kind": { "type": "string", "enum": ["sale", "refund"], "default": "sale" }\n',
]);

const OPENAPI_V1 = `# @generated by openapi-python-client 0.19.1 from api/tally.yaml. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class TotalResponse:
    account: str
    total: str
    currency: str

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TotalResponse:
        return cls(account=data["account"], total=data["total"], currency=data["currency"])

    def to_dict(self) -> dict[str, Any]:
        return {"account": self.account, "total": self.total, "currency": self.currency}
`;

const OPENAPI_V2 = edit(
  OPENAPI_V1,
  ['0.19.1', '0.21.0'],
  [
    `    account: str
    total: str
    currency: str

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TotalResponse:
        return cls(account=data["account"], total=data["total"], currency=data["currency"])

    def to_dict(self) -> dict[str, Any]:
        return {"account": self.account, "total": self.total, "currency": self.currency}
`,
    `    account: str
    total: str
    currency: str
    refunds: str = "0"

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TotalResponse:
        return cls(
            account=data["account"],
            total=data["total"],
            currency=data["currency"],
            refunds=data.get("refunds", "0"),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "account": self.account,
            "total": self.total,
            "currency": self.currency,
            "refunds": self.refunds,
        }
`,
  ],
);

const LOCK_V1 = `# This file is autogenerated by pip-compile; do not edit by hand.
pytest==8.1.1 \\
    --hash=sha256:2a8386cfc11fa9d2c50ee7b2a57e7d898ef90470a7a34c4b949ff59662bb78b7
pluggy==1.4.0 \\
    --hash=sha256:7db9f7b503d67d1c5b95f59773ebb58a8c1c288129a88665838012cfb07b8981
iniconfig==2.0.0 \\
    --hash=sha256:b6a85871a79d2e3b22d2d1b94ac2824226a63c6b741c88f7ae975f18b6778374
packaging==24.0 \\
    --hash=sha256:2ddfb553fdf02fb784c234c7ba6ccc288296ceabec964ad2eae3777778130bc5
`;

const LOCK_V2 = edit(
  LOCK_V1,
  [
    'pytest==8.1.1 \\\n    --hash=sha256:2a8386cfc11fa9d2c50ee7b2a57e7d898ef90470a7a34c4b949ff59662bb78b7\n',
    'pytest==8.2.0 \\\n    --hash=sha256:1733f0620f6cda4095bbf0d9ff8022486e91892245bb9e7d5542c018f612f233\n',
  ],
  [
    'pluggy==1.4.0 \\\n    --hash=sha256:7db9f7b503d67d1c5b95f59773ebb58a8c1c288129a88665838012cfb07b8981\n',
    'pluggy==1.5.0 \\\n    --hash=sha256:44e1ad92c8ca002de6377e165f3e0f1be63266ab4d554740532335b9d75ea669\n',
  ],
);

const GUIDE = `# Übersicht

tally liest Kassenbücher im CSV-Format und summiert sie pro Konto.

| Spalte        | Bedeutung                        |
| ------------- | -------------------------------- |
| \`account\`     | Konto, z. B. \`travel\`            |
| \`description\` | Freitext                         |
| \`quantity\`    | Stückzahl                        |
| \`unit_price\`  | Einzelpreis als Dezimalzahl      |
| \`currency\`    | ISO-4217-Code, Standard \`EUR\`    |

Beträge werden auf die kleinste Einheit der Währung gerundet: 0 Stellen bei JPY,
3 bei KWD, sonst 2.
`;

const RELEASE_NOTES = `# Release notes

## 0.1.0

- \`tally total\` sums one or many CSV ledgers per account.
- Totals round to the currency's minor unit.
- Mixed currencies within one total are an error; use \`totals_by_currency\`.
`;

const TALLY_SH = `#!/usr/bin/env bash
# Run tally from a checkout without installing it.
set -euo pipefail
here="$(cd "$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
exec env PYTHONPATH="$here" python -m tally.cli "$@"
`;

/** CRLF on purpose: Windows batch files keep their endings, and the viewer must render them. */
const BUILD_BAT = [
  '@echo off',
  'rem Build the wheel on Windows.',
  'python -m pip install --upgrade build',
  'python -m build --wheel',
  'if errorlevel 1 exit /b 1',
  'echo done',
  '',
].join('\r\n');

const INDEX_HTML = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>tally</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <main>
      <h1><img src="../assets/logo.png" alt="" width="16" height="16" /> tally</h1>
      <table id="totals">
        <thead>
          <tr><th>Account</th><th>Total</th></tr>
        </thead>
        <tbody></tbody>
      </table>
    </main>
    <script type="module" src="app.js"></script>
  </body>
</html>
`;

const APP_TS = `// Renders the totals \`tally total --json\` prints into the table.
interface Totals {
  [account: string]: string;
}

async function load(): Promise<Totals> {
  const response = await fetch('totals.json');
  if (!response.ok) throw new Error(\`totals.json: HTTP \${response.status}\`);
  return (await response.json()) as Totals;
}

function render(totals: Totals): void {
  const body = document.querySelector<HTMLTableSectionElement>('#totals tbody');
  if (!body) return;
  body.replaceChildren(
    ...Object.entries(totals).map(([account, total]) => {
      const row = document.createElement('tr');
      row.innerHTML = \`<td>\${account}</td><td class="amount">\${total}</td>\`;
      return row;
    }),
  );
}

load().then(render, (error: unknown) => {
  console.error(error);
});
`;

const STYLES_CSS = `:root {
  --ink: #1f2933;
  --paper: #fdfcf9;
  --accent: #2f6fed;
  font-family: system-ui, sans-serif;
}

body {
  margin: 0;
  color: var(--ink);
  background: var(--paper);
}

main {
  max-width: 40rem;
  margin: 3rem auto;
  padding: 0 1rem;
}

table {
  width: 100%;
  border-collapse: collapse;
}

th,
td {
  padding: 0.5rem 0.75rem;
  border-bottom: 1px solid color-mix(in srgb, var(--ink) 15%, transparent);
  text-align: left;
}

td.amount {
  font-variant-numeric: tabular-nums;
  text-align: right;
}
`;

/** One minified line, the shape the viewer must wrap or scroll rather than choke on. */
const SPARKLINE_MIN_JS =
  '/*! sparkline 0.3.2 | MIT */!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?module.exports=t():"function"==typeof define&&define.amd?define(t):(e=e||self).sparkline=t()}(this,function(){"use strict";function e(e,t,n){return Math.max(t,Math.min(n,e))}function t(t,n,r){var o=Math.max.apply(null,t),i=Math.min.apply(null,t),a=o-i||1;return t.map(function(t,o){return[o/(t.length-1||1)*n,r-e((t-i)/a,0,1)*r]})}return function(n,r,o){void 0===o&&(o={});var i=o.width||120,a=o.height||24,c=o.stroke||"currentColor",u=t(r,i,a),l="M"+u.map(function(e){return e.join(",")}).join("L");n.setAttribute("viewBox","0 0 "+i+" "+a);var s=document.createElementNS("http://www.w3.org/2000/svg","path");return s.setAttribute("d",l),s.setAttribute("fill","none"),s.setAttribute("stroke",c),s.setAttribute("stroke-width",String(o.strokeWidth||1.5)),n.replaceChildren(s),n}});\n';

const NOTES_TODO = `# Before merging

- [ ] decide whether refunds without a matching sale should fail the run
- [ ] mention \`kind\` in the README table
- [x] regenerate the OpenAPI client
`;

/** 4x4 PNGs; embedded rather than encoded at build time so no compressor version leaks into the hashes. */
const LOGO_V1 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAEElEQVR42mPQz38LRwzEcQB2Uhix5WLNPAAAAABJRU5ErkJggg==',
  'base64',
);
const LOGO_V2 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAEElEQVR42mN4m68PRwzEcQCOEhixpvTqiQAAAABJRU5ErkJggg==',
  'base64',
);

// ---------------------------------------------------------------------------------------------
// History.

const HISTORY: Commit[] = [
  {
    message: 'chore: scaffold tally',
    author: 'ada',
    files: {
      '.gitattributes': GITATTRIBUTES,
      '.gitignore': GITIGNORE,
      'README.md': README_V1,
      'pyproject.toml': PYPROJECT,
      'tally/__init__.py': INIT_PY,
      'tally/ledger.py': LEDGER_V1,
      'tally/cli.py': CLI_V1,
      'tally/legacy.py': LEGACY,
      'tally/schema.json': SCHEMA_V1,
      'tests/test_ledger.py': TEST_LEDGER_V1,
    },
  },
  {
    message: 'feat(ledger): round totals per currency',
    author: 'grace',
    files: {
      'tally/money.py': MONEY,
      'tally/ledger.py': LEDGER_V2,
      'tests/test_ledger.py': TEST_LEDGER_V2,
    },
  },
  {
    message: 'docs: add a user guide and release notes',
    author: 'ada',
    files: {
      'docs/Übersicht.md': GUIDE,
      'docs/release notes.md': RELEASE_NOTES,
    },
    tag: TAG,
  },
  {
    message: 'feat(cli): add --json output and a web preview',
    author: 'grace',
    files: {
      'tally/cli.py': CLI_V2,
      'scripts/tally.sh': TALLY_SH,
      'assets/logo.png': LOGO_V1,
      'web/index.html': INDEX_HTML,
      'web/app.ts': APP_TS,
      'web/styles.css': STYLES_CSS,
      'tally/generated/openapi.py': OPENAPI_V1,
      'requirements.lock': LOCK_V1,
    },
  },
  {
    branch: FEATURE_BRANCH,
    message: 'feat(ledger): support refund lines',
    author: 'ada',
    files: {
      'tally/ledger.py': LEDGER_V3,
      'tally/refunds.py': REFUNDS_V1,
      'tests/test_ledger.py': TEST_LEDGER_V3,
      'tests/test_refunds.py': TEST_REFUNDS,
    },
  },
  {
    message: 'refactor: move money helpers into a currency module',
    author: 'grace',
    moves: [
      ['tally/money.py', 'tally/currency.py'],
      ['docs/Übersicht.md', 'docs/guide/Übersicht.md'],
    ],
    files: {
      'tally/currency.py': CURRENCY,
      'tally/ledger.py': LEDGER_V4,
      'tally/refunds.py': REFUNDS,
    },
    exec: ['scripts/tally.sh'],
  },
  {
    message: 'chore: regenerate the client, refresh the lockfile and the logo',
    author: 'ada',
    files: {
      'tally/generated/openapi.py': OPENAPI_V2,
      'tally/schema.json': SCHEMA_V2,
      'requirements.lock': LOCK_V2,
      'assets/logo.png': LOGO_V2,
      'tally/legacy.py': null,
      'tally/py.typed': '',
      'web/vendor/sparkline.min.js': SPARKLINE_MIN_JS,
      'scripts/build.bat': BUILD_BAT,
      VERSION: '0.2.0',
    },
  },
  {
    checkout: MAIN_BRANCH,
    message: 'fix(ledger): reject negative quantities',
    author: 'grace',
    files: {
      'tally/ledger.py': LEDGER_MAIN_FIX,
      'README.md': README_V2,
    },
  },
  {
    checkout: FEATURE_BRANCH,
    message:
      'fix(cli): report an empty ledger instead of crashing\n\n' +
      'A ledger with only a header row produced "total: 0" and exit code 0, which\n' +
      'hid a wrong glob in cron jobs. Print a message to stderr and exit 1 instead.',
    author: 'grace',
    files: {
      'tally/cli.py': CLI_V3,
    },
  },
];

/** Uncommitted state left in the checkout, for `working` mode. */
const WORKTREE = {
  staged: { 'tally/refunds.py': REFUNDS_STAGED } satisfies Files,
  unstaged: { 'README.md': README_WORKTREE } satisfies Files,
  untracked: { 'notes/todo.md': NOTES_TODO } satisfies Files,
};

// ---------------------------------------------------------------------------------------------
// Builder.

export interface FixtureRepo {
  dir: string;
  /** Commit hashes by branch and tag name; stable across machines. */
  refs: Record<string, string>;
}

/** No user config, no hooks, no line-ending conversion: only this file decides what gets hashed. */
const GIT_ARGS = [
  '-c',
  'core.autocrlf=false',
  '-c',
  'core.safecrlf=false',
  '-c',
  'core.quotepath=false',
  '-c',
  'commit.gpgsign=false',
  '-c',
  'tag.gpgsign=false',
];

/** Build the fixture repository in `dir`, replacing whatever is there. */
export async function buildFixtureRepo(dir: string): Promise<FixtureRepo> {
  await rm(dir, { recursive: true, force: true });
  await mkdir(dir, { recursive: true });

  let commits = 0;
  const git = (args: string[], author: Author = 'ada'): string => {
    const date = new Date(EPOCH + commits * 3_600_000).toISOString();
    const who = AUTHORS[author];
    return execFileSync('git', [...GIT_ARGS, ...args], {
      cwd: dir,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
      env: {
        ...process.env,
        GIT_CONFIG_GLOBAL: '/dev/null',
        GIT_CONFIG_NOSYSTEM: '1',
        GIT_AUTHOR_NAME: who.name,
        GIT_AUTHOR_EMAIL: who.email,
        GIT_COMMITTER_NAME: who.name,
        GIT_COMMITTER_EMAIL: who.email,
        GIT_AUTHOR_DATE: date,
        GIT_COMMITTER_DATE: date,
      },
    }).trim();
  };

  const write = async (files: Files) => {
    for (const [path, content] of Object.entries(files)) {
      const target = join(dir, path);
      if (content === null) {
        await rm(target);
      } else {
        await mkdir(dirname(target), { recursive: true });
        await writeFile(target, content);
      }
    }
  };

  // `--template=` skips the sample hooks, which are noise in a fixture and differ between Git builds.
  git(['init', '-q', '-b', MAIN_BRANCH, '--template=']);

  for (const commit of HISTORY) {
    if (commit.checkout) git(['checkout', '-q', commit.checkout]);
    if (commit.branch) git(['checkout', '-q', '-b', commit.branch]);
    for (const [from, to] of commit.moves ?? []) {
      await mkdir(dirname(join(dir, to)), { recursive: true });
      git(['mv', from, to]);
    }
    await write(commit.files ?? {});
    git(['add', '-A']);
    for (const path of commit.exec ?? []) {
      // The index bit is what gets committed; the chmod only makes the checkout runnable on POSIX.
      git(['update-index', '--chmod=+x', path]);
      if (process.platform !== 'win32') await chmod(join(dir, path), 0o755);
    }
    git(['commit', '-q', '-m', commit.message], commit.author);
    if (commit.tag) git(['tag', '-a', commit.tag, '-m', `tally ${commit.tag.slice(1)}`], commit.author);
    commits++;
  }

  await write(WORKTREE.staged);
  git(['add', ...Object.keys(WORKTREE.staged)]);
  await write(WORKTREE.unstaged);
  await write(WORKTREE.untracked);

  const refs: Record<string, string> = {};
  for (const ref of [MAIN_BRANCH, FEATURE_BRANCH, TAG]) refs[ref] = git(['rev-parse', `${ref}^{commit}`]);
  return { dir, refs };
}
