# yaml-language-server: $schema=https://raw.githubusercontent.com/octo-sts/app/refs/heads/main/pkg/octosts/octosts.TrustPolicy.json
issuer: https://token.actions.githubusercontent.com
subject: repo:moritzwilksch@58488209/diffle@1361878265:ref:refs/heads/main
claim_pattern:
  event_name: ^(push|workflow_dispatch)$
  job_workflow_ref: ^moritzwilksch/diffle/\.github/workflows/release\.yml@refs/heads/main$

permissions:
  contents: write
  pull_requests: write
