import { describe, expect, it } from 'vitest';
import { looksGenerated, SNIFF_BYTES } from '../../src/server/generated.js';

const buf = (s: string) => Buffer.from(s, 'utf8');

describe('looksGenerated', () => {
  it('matches lockfiles, minified bundles, protobuf output and generated directories by path alone', () => {
    for (const p of ['package-lock.json', 'sub/yarn.lock', 'Cargo.lock', 'app.min.js', 'x/app.min.css', 'a.js.map', 'proto/x_pb2.py', 'x.pb.go', 'src/__snapshots__/a.snap', 'generated/schema.ts', 'lib/api.generated.ts']) {
      expect(looksGenerated(p, null), p).toBe(true);
    }
    for (const p of ['src/main.py', 'lock.py', 'minified.md', 'generate.py', 'src/generated_at.py']) {
      expect(looksGenerated(p, buf('plain\n')), p).toBe(false);
    }
  });

  it('sniffs the header for generator markers and never flags binary content', () => {
    expect(looksGenerated('a.py', buf('# @generated by protoc\n'))).toBe(true);
    expect(looksGenerated('a.go', buf('// Code generated by mockery. DO NOT EDIT.\n'))).toBe(true);
    expect(looksGenerated('a.ts', buf('/* eslint-disable */\n// This file was automatically generated.\n'))).toBe(true);
    expect(looksGenerated('a.py', buf('def generated_at():\n    pass\n'))).toBe(false);
    // Mentions outside a comment: prose, or code that handles the markers.
    expect(looksGenerated('README.md', buf('Files with `@generated` or `DO NOT EDIT` headers start collapsed.\n'))).toBe(false);
    expect(looksGenerated('gen.ts', buf("const MARKERS = [/@generated/, /DO NOT EDIT/];\n"))).toBe(false);
    expect(looksGenerated('a.html', buf('<!doctype html>\n<!-- @generated by docs-build -->\n'))).toBe(true);
    expect(looksGenerated('a.py', null)).toBe(false);
    expect(looksGenerated('a.py', Buffer.alloc(0))).toBe(false);
    expect(looksGenerated('a.bin', Buffer.concat([buf('@generated'), Buffer.from([0, 1, 2])]))).toBe(false);
    // Only the first SNIFF_BYTES count.
    expect(looksGenerated('a.py', buf('x'.repeat(SNIFF_BYTES) + '\n# @generated\n'))).toBe(false);
  });
});
